# Generated by Django 4.1 on 2022-12-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('lancamento', models.DateField()),
                ('diretor', models.CharField(default='Não Especificado', max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('capa', models.ImageField(null=True, upload_to='')),
                ('idioma', models.CharField(max_length=10)),
                ('horario', models.CharField(max_length=30)),
                ('sala', models.CharField(max_length=10)),
                ('sinopse', models.TextField()),
            ],
        ),
    ]
