# Generated by Django 4.1 on 2022-12-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarios_filmes', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='filme',
            name='horario',
        ),
        migrations.AlterField(
            model_name='filme',
            name='capa',
            field=models.ImageField(default=1, upload_to='capa_filme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filme',
            name='horarios_filmes',
            field=models.ManyToManyField(to='star_cinema.horarios'),
        ),
    ]
