# Generated by Django 4.1 on 2022-12-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('star_cinema', '0002_horarios_remove_filme_horario_alter_filme_capa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarios',
            old_name='horarios_filmes',
            new_name='horarios',
        ),
    ]
